name: presentation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.4.0
  json_annotation: ^4.7.0
  cloud_firestore: ^4.2.0
  google_fonts: ^3.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: ^2.1.10
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

