// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXi0wqywAwI7nW-asQCDtbIkRT13uu-FU',
    appId: '1:390429138714:web:3c7ba086bb164d8b0dd6a3',
    messagingSenderId: '390429138714',
    projectId: 'presentation-b4c9f',
    authDomain: 'presentation-b4c9f.firebaseapp.com',
    storageBucket: 'presentation-b4c9f.appspot.com',
    measurementId: 'G-0TN0WQVRJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nm11XO7NadfyPVSIim5zjrHlHOoW8xY',
    appId: '1:390429138714:android:27b9adffae5fe4c70dd6a3',
    messagingSenderId: '390429138714',
    projectId: 'presentation-b4c9f',
    storageBucket: 'presentation-b4c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVGN3YLxizhWe0B1k4yty0JadStYL1yPU',
    appId: '1:390429138714:ios:f882c6922d85cb570dd6a3',
    messagingSenderId: '390429138714',
    projectId: 'presentation-b4c9f',
    storageBucket: 'presentation-b4c9f.appspot.com',
    iosClientId: '390429138714-rjsdpqc1ji7rc1155r2o15ucmvbuqaib.apps.googleusercontent.com',
    iosBundleId: 'com.presentation.presentation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVGN3YLxizhWe0B1k4yty0JadStYL1yPU',
    appId: '1:390429138714:ios:f882c6922d85cb570dd6a3',
    messagingSenderId: '390429138714',
    projectId: 'presentation-b4c9f',
    storageBucket: 'presentation-b4c9f.appspot.com',
    iosClientId: '390429138714-rjsdpqc1ji7rc1155r2o15ucmvbuqaib.apps.googleusercontent.com',
    iosBundleId: 'com.presentation.presentation',
  );
}
